### ISSUE TITLE
Filtering by meta attribute results in NPE

### ISSUE THREAD

**Issue by psvo** [Captain-P-Goldfish/SCIM-SDK#168]
When automatic filtering is enabled and filter by meta attribute is used, for example `meta.created eq "2000-10-10T00:00:00.000Z"`, NullPointerException is thrown when processing request.

It's caused by meta attribute being evaluated as extension attribute, but although it internally has it's own schema, it's not (and should not be) registered as an extension.

```
[...snip...]
Caused by: java.lang.NullPointerException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603) ~[?:?]
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678) ~[?:?]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at de.captaingoldfish.scim.sdk.server.filter.resources.FilterResourceResolver.filterResources(FilterResourceResolver.java:50) ~[scim-sdk-server-1.10.0.jar:?]
	at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpointHandler.filterResources(ResourceEndpointHandler.java:654) ~[scim-sdk-server-1.10.0.jar:?]
	at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpointHandler.listResources(ResourceEndpointHandler.java:544) ~[scim-sdk-server-1.10.0.jar:?]
	... 81 more
Caused by: java.lang.NullPointerException
	at de.captaingoldfish.scim.sdk.server.filter.resources.FilterResourceResolver.retrieveComplexAttributeNode(FilterResourceResolver.java:170) ~[scim-sdk-server-1.10.0.jar:?]
	at de.captaingoldfish.scim.sdk.server.filter.resources.FilterResourceResolver.visitAttributeExpressionLeaf(FilterResourceResolver.java:120) ~[scim-sdk-server-1.10.0.jar:?]
	at de.captaingoldfish.scim.sdk.server.filter.resources.FilterResourceResolver.isResourceMatchingFilter(FilterResourceResolver.java:92) ~[scim-sdk-server-1.10.0.jar:?]
	at de.captaingoldfish.scim.sdk.server.filter.resources.FilterResourceResolver.lambda$getResourcePredicate$0(FilterResourceResolver.java:61) ~[scim-sdk-server-1.10.0.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952) ~[?:?]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926) ~[?:?]
	at java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
```

**Comment by Captain-P-Goldfish** [comment]
Fixed with your pull request
