### ISSUE TITLE
Logger error at start up

### ISSUE THREAD

**Issue by ahavriluk** [Captain-P-Goldfish/SCIM-SDK#386]
Hi! 

I have a Dropwizard app. As soon as I add this dependency to gradle 

```implementation "de.captaingoldfish:scim-sdk-server:1.15.2"```

I get this error on app startup: 

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/Users/ohavrylyuk/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.11/4741689214e9d1e8408b206506cbe76d1c6a7d60/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Exception in thread "main" java.lang.IllegalStateException: Unable to acquire the logger context
	at io.dropwizard.logging.LoggingUtil.getLoggerContext(LoggingUtil.java:46)
	at io.dropwizard.logging.BootstrapLogging.bootstrap(BootstrapLogging.java:51)
	at io.dropwizard.logging.BootstrapLogging.bootstrap(BootstrapLogging.java:40)
	at io.dropwizard.Application.bootstrapLogging(Application.java:38)
	at io.dropwizard.Application.<init>(Application.java:26)
	at com.appnexus.webservices.dropwizard.BaseApplication.<init>(BaseApplication.java:45)

Process finished with exit code 1
```

**Comment by Captain-P-Goldfish** [comment]
It seems your have a dependency problem with slf4j.
There are generally two ways to resolve this:
1. use gradles dependency management to downgrade slf4j-api globally to 1.7.x (https://docs.gradle.org/current/userguide/platforms.html)
2. update your slf4j-api dependencies to the newer 2.0.x version

**Comment by ahavriluk** [comment]
Thank you! This worked for me:

```
    implementation ("de.captaingoldfish:scim-sdk-server:1.15.2") {
        exclude group: 'org.slf4j'
    }
```
Which looks like #1 solution.
