### ISSUE TITLE
Keycloak-Example patch group member returns 500

### ISSUE THREAD

**Issue by csbrogi** [Captain-P-Goldfish/SCIM-SDK#4]
I try to patch an existing group with the following request
```
PATCH ..../auth/realms/Goldfish/scim/v2/Groups/d2ba0d0c-9536-4d61-beec-2b656170b0c8
{
	  "schemas": ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
	   "Operations": [   	
        {
          "op":"add",
        "path":"members",
        "value":[
        
        {
            "value": "1a463183-453d-467e-9ee5-602852754ba3",
            "type": "User"
        }
        ]
        }
    ]
 }

```
The user is assigned to the group, but the request returns an internal server error (500)
```
{
    "detail": "sorry but an internal error has occurred.",
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "status": 500
}

```
the stack-trace is:
```
15:00:11,077 ERROR [de.captaingoldfish.scim.sdk.server.schemas.SchemaValidator] (default task-46) meta attribute validation failed for resource type: Group [urn:ietf:params:scim:schemas:core:2.0:Group]
15:00:11,078 ERROR [de.captaingoldfish.scim.sdk.common.response.ErrorResponse] (default task-46) the attribute 'urn:ietf:params:scim:schemas:core:2.0:Meta:meta.resourceType' is required on response.
                name: 'resourceType'
                type: 'STRING'
                description: 'The name of the resource type of the resource. This attribute has a mutability of "readOnly" and "caseExact" as "true".'
                mutability: 'READ_ONLY'
                returned: 'DEFAULT'
                uniqueness: 'NONE'
                multivalued: 'false'
                required: 'true'
                caseExact: 'true': de.captaingoldfish.scim.sdk.common.exceptions.DocumentValidationException: the attribute 'urn:ietf:params:scim:schemas:core:2.0:Meta:meta.resourceType' is required on response.
                name: 'resourceType'
                type: 'STRING'
                description: 'The name of the resource type of the resource. This attribute has a mutability of "readOnly" and "caseExact" as "true".'
                mutability: 'READ_ONLY'
                returned: 'DEFAULT'
                uniqueness: 'NONE'
                multivalued: 'false'
                required: 'true'
                caseExact: 'true'
        at de.captaingoldfish.scim.sdk.server.schemas.SchemaValidator.getException(SchemaValidator.java:1287)
        at de.captaingoldfish.scim.sdk.server.schemas.SchemaValidator.validateIsRequiredForResponse(SchemaValidator.java:894)
        at de.captaingoldfish.scim.sdk.server.schemas.SchemaValidator.validateIsRequired(SchemaValidator.java:831)
        at de.captaingoldfish.scim.sdk.server.schemas.SchemaValidator.checkMetaAttributeOnDocument(SchemaValidator.java:577)
        at de.captaingoldfish.scim.sdk.server.schemas.SchemaValidator.validateAttributes(SchemaValidator.java:553)
        at de.captaingoldfish.scim.sdk.server.schemas.SchemaValidator.handleComplexNode(SchemaValidator.java:757)
        at de.captaingoldfish.scim.sdk.server.schemas.SchemaValidator.handleNode(SchemaValidator.java:736)
        at de.captaingoldfish.scim.sdk.server.schemas.SchemaValidator.checkMetaAttributeOnDocument(SchemaValidator.java:595)
        at de.captaingoldfish.scim.sdk.server.schemas.SchemaValidator.validateAttributes(SchemaValidator.java:553)
        at de.captaingoldfish.scim.sdk.server.schemas.SchemaValidator.validateDocument(SchemaValidator.java:524)
        at de.captaingoldfish.scim.sdk.server.schemas.SchemaValidator.validateExtensionForResponse(SchemaValidator.java:371)
        at de.captaingoldfish.scim.sdk.server.schemas.SchemaValidator.validateDocumentForResponse(SchemaValidator.java:261)
        at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpointHandler.patchResource(ResourceEndpointHandler.java:947)
        at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpoint.resolveRequest(ResourceEndpoint.java:178)
        at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpoint.handleRequest(ResourceEndpoint.java:98)
        at de.captaingoldfish.scim.sdk.keycloak.scim.ScimEndpoint.get(ScimEndpoint.java:80)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by Captain-P-Goldfish** [comment]
you are right.
there was a problem in case that a newly created meta-attribute was added to the resource. My unit-tests didn't catch that. I just fixed the problem and going to prepare a new release in the next few days

**Comment by csbrogi** [comment]
Thanks for the quick fix.
