### ISSUE TITLE
Resource IDs with spaces in them cause an invalid location URI to be generated

### ISSUE THREAD

**Issue by mberning** [Captain-P-Goldfish/SCIM-SDK#452]
Some end systems use resource IDs which have spaces in the value. This causes a validation error when SCIM-SDK is generating the location metadata for a resource as the resource ID is not currently being URL escaped.

I have modified a version of the springboot example which demonstrates the issue here: https://github.com/mberning/SCIM-SDK/compare/master...bad-location-uri-example

Example: A Group with a resource ID of "super admin"

Request:
```bash
curl "http://localhost:8080/scim/v2/Groups"
```

Response:
```json
{
  "detail": "An internal error has occurred.",
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:Error"
  ],
  "status": 500
}
```

Stacktrace:
```
24 Mar 2023 16:20:24,766 [http-nio-8080-exec-2] ERROR de.captaingoldfish.scim.sdk.common.response.ErrorResponse (ErrorResponse.java:63) - Attribute 'urn:ietf:params:scim:schemas:core:2.0:Meta:meta.location' is a referenceType and must apply to one of the following types '[URI]' but value is 'http://localhost:8080/scim/v2/Groups/super admin'
de.captaingoldfish.scim.sdk.common.exceptions.InternalServerException: Attribute 'urn:ietf:params:scim:schemas:core:2.0:Meta:meta.location' is a referenceType and must apply to one of the following types '[URI]' but value is 'http://localhost:8080/scim/v2/Groups/super admin'
	at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpointHandler.listResources(ResourceEndpointHandler.java:629)
	at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpoint.resolveRequest(ResourceEndpoint.java:255)
	at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpoint.handleRequest(ResourceEndpoint.java:190)
	at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpoint.handleRequest(ResourceEndpoint.java:77)
	at de.captaingoldfish.scim.sdk.springboot.sample.controller.ScimController.handleScimRequest(ScimController.java:68)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: de.captaingoldfish.scim.sdk.server.schemas.exceptions.AttributeValidationException: Attribute 'urn:ietf:params:scim:schemas:core:2.0:Meta:meta.location' is a referenceType and must apply to one of the following types '[URI]' but value is 'http://localhost:8080/scim/v2/Groups/super admin'
	at de.captaingoldfish.scim.sdk.server.schemas.validation.SimpleAttributeValidator.validateValueNodeWithReferenceTypes(SimpleAttributeValidator.java:206)
	at de.captaingoldfish.scim.sdk.server.schemas.validation.SimpleAttributeValidator.parseNodeType(SimpleAttributeValidator.java:125)
	at de.captaingoldfish.scim.sdk.server.schemas.validation.ValidationSelector.validateNode(ValidationSelector.java:83)
	at de.captaingoldfish.scim.sdk.server.schemas.validation.ComplexAttributeValidator.parseNodeType(ComplexAttributeValidator.java:50)
	at de.captaingoldfish.scim.sdk.server.schemas.validation.ValidationSelector.validateNode(ValidationSelector.java:76)
	at de.captaingoldfish.scim.sdk.server.schemas.validation.ResponseAttributeValidator.validateAttribute(ResponseAttributeValidator.java:245)
	at de.captaingoldfish.scim.sdk.server.schemas.validation.ResponseSchemaValidator.validateAttribute(ResponseSchemaValidator.java:63)
	at de.captaingoldfish.scim.sdk.server.schemas.validation.AbstractSchemaValidator.validateDocument(AbstractSchemaValidator.java:128)
	at de.captaingoldfish.scim.sdk.server.schemas.validation.ResponseResourceValidator.validateDocument(ResponseResourceValidator.java:48)
	at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpointHandler.listResources(ResourceEndpointHandler.java:616)
	... 44 more
```

I will submit a PR which resolves this issue and reference this issue in the commit messages.

**Comment by Captain-P-Goldfish** [comment]
Hi I can think of two solutions.
The current problem is that the location attribute is expected to be a URI and a URI does not define whitespace characters.


solution 1:
set the location manually and encode the id 
```
String resourceLocation = context.getResourceReferenceUrl(URLEncoder.encode(id, StandardCharsets.UTF_8));
resource.getMeta().get().setLocation(resourceLocation);
```

solution 2 (hacky solution):
the `ResourceTypeFactory` of the `ResourceEndpoint` has a protected getter-method. You could use this circumstance to provide a bridge-class that gets access to this method. If you do, you can do the following: 
```
ResourceTypeFactory resourceTypeFactory = resourceEndpoint.getResourceTypeFactory();
SchemaAttribute metaLocation = resourceTypeFactory.getSchemaFactory().getMetaSchema(SchemaUris.META).getSchemaAttribute("meta.location");
metaLocation.setReferenceTypes(null);
metaLocation.setType(Type.STRING)

**Comment by Captain-P-Goldfish** [comment]
> I tried solution #1 but unfortunately it looks like the `listResources` method in `ResourceEndpointHandler` is overwriting the location on this line:
> 
> https://github.com/Captain-P-Goldfish/SCIM-SDK/blob/a57fe0745ad2dbdf574cd5943b3bb90592c7d44e/scim-sdk-server/src/main/java/de/captaingoldfish/scim/sdk/server/endpoints/ResourceEndpointHandler.java#L608

I am not quite happy with the pull-request solution yet, because this might result in problems for developers that are not fully aware of the ur-encoding part.

I am also a bit irritated. I verified what you said, that the location attribute is overridden even if you are setting it yourself. I consider this a serious bug. I was also sure that I wrote a test once that proves that my app is not overriding this attribute. In my eyes this is what should be fixed.

**Comment by Captain-P-Goldfish** [comment]
> I tried solution #1 but unfortunately it looks like the `listResources` method in `ResourceEndpointHandler` is overwriting the location on this line:
> 
> https://github.com/Captain-P-Goldfish/SCIM-SDK/blob/a57fe0745ad2dbdf574cd5943b3bb90592c7d44e/scim-sdk-server/src/main/java/de/captaingoldfish/scim/sdk/server/endpoints/ResourceEndpointHandler.java#L608

I could verify this behaviour and I consider this a serious bug. I think its a better option to fix this instead of adding arbitrary url encoding into the source code that might be unexpected by some users.

**Comment by Captain-P-Goldfish** [comment]
Do you want to fix it or shall I do it?

**Comment by mberning** [comment]
> Do you want to fix it or shall I do it?

I will fix it. The issue appears in two places, the `listResources` and `getResource` method.

**Comment by mberning** [comment]
I have found another issue related to this which I have demonstrated in my branch: https://github.com/mberning/SCIM-SDK/commit/2028e50586d9974155922cfd9074627c39fb0676

The issue is this: Suppose that the end system creates the ID based off of the display name of the group. The group will be created successfully, but the group can never be retrieved by calling the `/Groups/{id}` endpoint because the space is never decoded. You can see this below.

```bash
➜  SCIM-SDK git:(bad-location-uri-example) ✗ curl -X "POST" "http://localhost:8080/scim/v2/Groups" \
     -H 'Content-Type: application/scim+json' \
     -d $'{
  "displayName": "Group A"
}'
{
  "schemas" : [ "urn:ietf:params:scim:schemas:core:2.0:Group" ],
  "id" : "Group A",
  "displayName" : "Group A",
  "meta" : {
    "resourceType" : "Group",
    "created" : "2023-03-27T03:26:22.948Z",
    "lastModified" : "2023-03-27T03:26:22.948Z",
    "location" : "http://localhost:8080/scim/v2/Groups/Group+A"
  }
}%
➜  SCIM-SDK git:(bad-location-uri-example) ✗ curl "http://localhost:8080/scim/v2/Groups/Group%20A"
{
  "detail" : "the 'Group' resource with id 'Group%20A' does not exist",
  "schemas" : [ "urn:ietf:params:scim:api:messages:2.0:Error" ],
  "status" : 404
}%
```

I have resolved this issue in my project by improving how the `uriInfos` object is being created in the `ResourceEndpoint`. I will propose something similar as part of this PR. Will submit something tomorrow.

**Comment by Captain-P-Goldfish** [comment]
> > Do you want to fix it or shall I do it?
> 
> I will fix it. The issue appears in two places, the `listResources` and `getResource` method.

Its also occuring in the other methods. It seems to be an issue for all endpoints. I somehow missed to write tests for this case.
