### ISSUE TITLE
With autoFiltering enabled, and invalid compare operator causes Null Pointer Exception

### ISSUE THREAD

**Issue by prthakre** [Captain-P-Goldfish/SCIM-SDK#650]
`/scim/v2/Users/?filter=userType eq1 "unknown"`. 
Please note the invalid compare operator **eq1** in the filter.
Exception: 
  `Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "filterNode" is null
	at de.captaingoldfish.scim.sdk.server.filter.resources.FilterResourceResolver.isResourceMatchingFilter(FilterResourceResolver.java:88)
	at de.captaingoldfish.scim.sdk.server.filter.resources.FilterResourceResolver.isResourceMatchingFilter(FilterResourceResolver.java:112)
	at de.captaingoldfish.scim.sdk.server.filter.resources.FilterResourceResolver.lambda$getResourcePredicate$1(FilterResourceResolver.java:76)
...	de.captaingoldfish.scim.sdk.server.filter.resources.FilterResourceResolver.lambda$filterResources$0(FilterResourceResolver.java:59)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1456)
	`

**Comment by Captain-P-Goldfish** [comment]
This seems to be a bug in antlr. The expression is not correctly resolved and everything from eq1 to the end is truncated from the string instead of throwing an InvalidFilterException. I will add a manual check to throw an appropriate error in this case

**Comment by prthakre** [comment]
Indeed. My bad, I should have shared the `filterNode.toString()` contents.
Thanks a lot for the fix.
